name: Lint & build
on:
  workflow_dispatch:
  push:
    tags:
      - v*
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-build:
    uses: gethinode/.github/.github/workflows/lint-build.yml@v1
    with:
      package-manager: npm
      lint-script: lint
      build-command: npm run build:cache
      cache-key: hugo-template
    secrets: inherit
